---
#
# Docker Dependencies
#

- name: Install Docker (Debian Family).
  when: ansible_os_family == 'Debian'
  block:
    - name: Update apt cache.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      changed_when: false

    - name: Install Docker Package
      ansible.builtin.apt:
        name: ['docker.io', 'python3-docker', 'python3-dockerpty']
        state: present

    - name: Install Ngnix dependencies
      ansible.builtin.apt:
        name: ['cron']
        state: present

- name: Install Docker (RedHat).
  when: ansible_os_family == 'RedHat'
  block:
    - name: Install Dnf Repo Tools
      ansible.builtin.dnf:
        name: ['dnf-utils', 'device-mapper-persistent-data', 'lvm2']
        state: present

    - name: Install Docker Packages (RedHat).
      ansible.builtin.dnf:
        name: ['docker.io']
        state: present

    - name: Install Ngnix dependencies
      ansible.builtin.dnf:
        name: ['vixie-cron']
        state: present
