---
# tasks file for ansible-docker-keycloak
- name: Init vars
  ansible.builtin.import_tasks: "{{ role_path }}/tasks/init.yml"
  become: true
  tags:
    - always

- name: Install Dependencies
  ansible.builtin.import_tasks: "{{ role_path }}/tasks/install_dependencies.yml"
  become: true
  tags:
    - setup-all
    - setup-keycloak

- name: Create docker network
  community.docker.docker_network:
    name: "{{ keycloak_docker_network }}"
  when: keycloak_postgres_enabled
  tags:
    - always

- name: Setup Nginx
  ansible.builtin.import_tasks: "{{ role_path }}/tasks/setup_nginx.yml"
  become: true
  tags:
    - setup-nginx
    - setup-all

- name: Setup Docker
  ansible.builtin.import_tasks: "{{ role_path }}/tasks/setup_postgres_docker.yml"
  become: true
  tags:
    - setup-all
    - setup-postgres

- name: Setup Docker
  ansible.builtin.import_tasks: "{{ role_path }}/tasks/setup_keycloak_docker.yml"
  become: true
  tags:
    - setup-all
    - setup-keycloak

- name: Ensure Systemd Services stopped
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: stopped
    enabled: true
  with_items: "{{ keycloak_systemd_services_list }}"
  become: true
  tags:
    - setup-all
    - setup-keycloak
    - setup-postgres
    - setup-nginx

- name: Ensure No Nginx cache exists. Resolves Bad Gateway errors
  ansible.builtin.file:
    path: /var/cache/nginx
    state: absent
  tags:
    - always

- name: Ensure Systemd Services started
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items: "{{ keycloak_systemd_services_list }}"
  become: true
  tags:
    - setup-all
    - setup-keycloak
    - setup-postgres
    - setup-nginx
