---
#
# https://hub.docker.com/r/jboss/keycloak/tags
#

- name: Check keycloak_admin_password variable
  ansible.builtin.fail:
    msg: "Bailing out. this play requires 'keycloak_admin_password'"
  when: keycloak_admin_password is undefined

- name: Pull Keycloak Docker
  community.docker.docker_image:
    name: "{{ keycloak_docker_image }}"
    source: pull

- name: Ensure Install Directory Exists
  ansible.builtin.file:
    path: "{{ keycloak_install_directory }}"
    state: directory
    owner: "{{ keycloak_user_uid }}"
    group: "{{ keycloak_user_gid }}"
    mode: "0750"


- name: Ensure keycloak.service installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/keycloak.service.j2"
    dest: "{{ keycloak_systemd_path }}/keycloak.service"
    mode: "0640"
  notify:
    - reload systemd
  register: keycloak_systemd_service_result
