- name: Check keycloak_postgres_connection_username variable
  ansible.builtin.fail:
    msg: "Bailing out. this play requires 'keycloak_postgres_connection_username'"
  when: keycloak_postgres_connection_username is undefined

- name: Pull Postgres Docker
  community.docker.docker_image:
    name: "{{ keycloak_postgres_docker_image }}"
    source: pull
  when: keycloak_postgres_enabled|bool

- name: Ensure Install Postgres Directory Exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ keycloak_user_uid }}"
    group: "{{ keycloak_user_gid }}"
    mode: "0700"
  with_items:
    - "{{ keycloak_postgres_base_path }}"
    - "{{ keycloak_postgres_data_path }}"
  when: keycloak_postgres_enabled|bool

- name: Ensure keycloak-postgres.service installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/keycloak-postgres.service.j2"
    dest: "{{ keycloak_systemd_path }}/keycloak-postgres.service"
    mode: "0640"
  notify:
    - Reload systemd
  when: keycloak_postgres_enabled|bool

- name: Ensure postgres setting files are installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/env-postgres-psql.j2"
    dest: "{{ keycloak_postgres_base_path }}/env-postgres-psql"
    owner: "{{ keycloak_user_uid }}"
    group: "{{ keycloak_user_gid }}"
    mode: "0640"
  when: keycloak_postgres_enabled|bool

- name: Ensure keycloak-postgres.service doesn't exist
  ansible.builtin.file:
    path: "{{ keycloak_systemd_path }}/keycloak-postgres.service"
    state: absent
  notify:
    - Reload systemd
  when: not keycloak_postgres_enabled|bool
