---
# handlers file for ansible-docker-keycloak
# https://docs.ansible.com/ansible/latest/user_guide/playbooks_intro.html


- name: Stop keycloak
  ansible.builtin.systemd_service:
    name: keycloak
    state: stopped

- name: Start keycloak
  ansible.builtin.systemd_service:
    name: keycloak
    state: started

- name: Restart keycloak
  ansible.builtin.systemd_service:
    name: keycloak
    state: restarted

- name: Stop postgres
  ansible.builtin.systemd_service:
    name: postgres
    state: stopped

- name: Start postgres
  ansible.builtin.systemd_service:
    name: postgres
    state: started

- name: Restart postgres
  ansible.builtin.systemd_service:
    name: postgres
    state: restarted

- name: Reload ansible.builtin.systemd_service
  ansible.builtin.systemd_service:
    daemon_reload: true
