#jinja2: lstrip_blocks: "True"
FROM {{ keycloak_docker_image }} as builder

# Enable health and metrics support
ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true

# Configure a database vendor
ENV KC_DB=postgres

WORKDIR /opt/keycloak
# for demonstration purposes only, please make sure to use proper certificates in production instead
# RUN keytool -genkeypair -storepass password -storetype PKCS12 -keyalg RSA -keysize 2048 -dname "CN=server" -alias server -ext "SAN:c=DNS:localhost,IP:127.0.0.1" -keystore conf/server.keystore
RUN /opt/keycloak/bin/kc.sh build

FROM  {{ keycloak_docker_image }}
COPY --from=builder /opt/keycloak/ /opt/keycloak/

ENV KC_HOSTNAME=http://{{ keycloak_domain_name }}:8080
ENV KC_PROXY_HEADERS=forwarded
ENV KC_HTTP_ENABLED=true
# change these values to point to a running postgres instance
ENV KC_DB=postgres
ENV KC_DB_URL=jdbc:postgresql://keycloak-postgres:5432/{{ keycloak_postgres_db_name }}
ENV KC_DB_USERNAME={{ keycloak_postgres_connection_username }}
ENV KC_DB_PASSWORD={{ keycloak_postgres_connection_password }}
ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
